languageCode: en-us
title: puz-zel
paginate: 3
summaryLength: 500
baseURL: "https://puz-zel.com"

permalinks:
    posts: /:filename

taxonomies:
    tag: tags

markup:
    goldmark:
        renderer:
            unsafe: true

social:
    github: https://github.com/hazel-nut
    twitter: https://twitter.com/hazelnym

params:
    subtitle: crossword puzzles by hazel virdó
    enableRSS: false
    enableComments: false
    enableGoogleAnalytics: false

    dateFormat: "2 January 2006"

#    links:
#    - name: example
#      url: example.com
