baseURL: http://example.org/
languageCode: en-us
title: puz-zel
theme: mini
paginate: 3

markup:
    goldmark:
        renderer:
            unsafe: true

social:
    github: https://github.com/hazel-nut
    twitter: https://twitter.com/hazelnym

params:
    author: Hazel Virdó
    bio: yes hello this is puzzle
    description: description
    enableRSS: true
    enableComments: false
    enableGoogleAnalytics: false
    showPowerBy: false
    copyright: 'hello'

    dateFormat: "2 January 2006"

    links:
    - name: Example 1
      path: /example
    - name: Example 2
      path: /example
    - name: Example 3
      path: /example
