languageCode: en-us
title: puz-zel
summaryLength: 500
baseURL: "https://puz-zel.com"

permalinks:
    posts: /:contentbasename

taxonomies:
    tag: tags

markup:
    goldmark:
        renderer:
            unsafe: true


params:
    social:
        github: https://github.com/hazel-nut
    subtitle: crossword puzzles by hazel virdó
    enableRSS: false
    enableComments: false
    enableGoogleAnalytics: false

    dateFormat: "2 January 2006"

#    links:
#    - name: example
#      url: example.com
