languageCode: en-us
title: puz-zel
paginate: 3

taxonomies:
    tag: tags

markup:
    goldmark:
        renderer:
            unsafe: true

social:
    github: https://github.com/hazel-nut
    twitter: https://twitter.com/hazelnym

params:
    subtitle: yes hello this is puzzle
    enableRSS: false
    enableComments: false
    enableGoogleAnalytics: false

    dateFormat: "2 January 2006"

#    links:
#    - name: example
#      url: example.com
